### ISSUE TITLE
Support php 7.4.9

### ISSUE THREAD

**Issue by Carpenter0100** [psr7-sessions/storageless#137]
Hi all, 
thank you for this project.
Is it possible to support php 7.4.9?

```
Composer

Problem 1
    - psr7-sessions/storageless 7.2.x-dev requires php ^7.4.7 -> your PHP version (7.4.9)
```

Thank you

**Comment by Ocramius** [comment]
This expression:

https://github.com/psr7-sessions/storageless/blob/9ff0c88a0fe27facb29a9588989c219aa8d9692e/composer.json#L24

Already supports `7.4.9`, since `^7.4.7` means `>=7.4.7 && <8`

Something else going on here, I think.

Have you tried using a stable version? You seem to rely on `7.2.x-dev`

**Comment by Carpenter0100** [comment]
You are right. Thank you.
I found a wrong dependency definition in my composer.json.
