### ISSUE TITLE
unable to use get() method

### ISSUE THREAD

**Issue by hatrena** [psr7-sessions/storageless#52]
When i use `$session->set()` and `$session->get()` immediately after it, everything works properly. but after that in the same page (Middleware), when i comment out `$session->set()`, `$session->get()` does give me nothing:

`$session = $request->getAttribute(\PSR7Session\Http\SessionMiddleware::SESSION_ATTRIBUTE);`
`//$session->set('user', 'Saeed');`
`echo $session->get('user');`

**Comment by Ocramius** [comment]
Did your cookies get transmitted at all? What is the cookie like? Can you try checking its contents?

**Comment by hatrena** [comment]
is there any specific variable that i need to look for in COOKIE? i have `PHPSESSID`

**Comment by Ocramius** [comment]
This lib doesn't use PHPSESSID: it has its own cookie called 'slsession'

is there any specific variable that i need to look for in COOKIE? i have
PHPSESSID

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/Ocramius/PSR7Session/issues/52#issuecomment-232023172>,
or mute the thread
<https://github.com/notifications/unsubscribe/AAJakA8Thecr_qgAPPKBFxdzUE41kJ9Dks5qU3_qgaJpZM4JKTQD>
.

**Comment by hatrena** [comment]
The Cookie does not have `slsession`? any workaround to fix?

**Comment by Ocramius** [comment]
Did you try any of the examples first?

**Comment by hatrena** [comment]
yes, i have the same problem

**Comment by Ocramius** [comment]
The counter example won't work either? Wondering if you can share how you have set it up...

**Comment by hatrena** [comment]
I am using  Zend Expressive and pipe it via `SessionMiddleware`:

'middleware_pipeline' => [
            'pre_routing' => [
                'middleware' => [
                    ServerUrlMiddleware::class,
                    QueryStringMiddleware::class,
                ],
                'priority' => PHP_INT_MAX,
            ],
            'routing' => [
                'middleware' => [
                    ApplicationFactory::ROUTING_MIDDLEWARE,
                    UrlHelperMiddleware::class,
                    SessionMiddleware::class,
                    ApplicationFactory::DISPATCH_MIDDLEWARE,
                ],
                'priority' => 1,
            ],
        ]

 and in `SessionMiddleware i have: 
return SessionMiddleware::fromSymmetricKeyDefaults(
        'MyKey',
         1200 
      );

**Comment by Ocramius** [comment]
Please try out the examples in this project first, and ensure that the
counter example works (you just need to run it, no coding needed)
On 12 Jul 2016 2:16 p.m., "Saeed Mohammadian" <notifications@github.com>
wrote:

I am using Zend Expressive and pipe it via SessionMiddleware:

'middleware_pipeline' => [
'pre_routing' => [
'middleware' => [
ServerUrlMiddleware::class,
QueryStringMiddleware::class,
],
'priority' => PHP_INT_MAX,
],
'routing' => [
'middleware' => [
ApplicationFactory::ROUTING_MIDDLEWARE,
UrlHelperMiddleware::class,
SessionMiddleware::class,
ApplicationFactory::DISPATCH_MIDDLEWARE,
],
'priority' => 1,
],
]

and in `SessionMiddleware i have:
return SessionMiddleware::fromSymmetricKeyDefaults(
'MyKey',
1200
);

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/Ocramius/PSR7Session/issues/52#issuecomment-232029948>,
or mute the thread
<https://github.com/notifications/unsubscribe/AAJakGDG5Q2VoCtpsy5ILwz2AZCSGvzUks5qU4WcgaJpZM4JKTQD>
.

**Comment by hatrena** [comment]
I have tested the `counter`, it shows `1` all the time, when i refresh the page

**Comment by Ocramius** [comment]
Try:

```sh
mkdir tst
cd tst
git clone git@github.com:Ocramius/PSR7Session.git
cd PSR7Session
composer install
php -S localhost:8080 examples/index.php
```

Now browse to `http://localhost:8080` and you should see a counter increment at each page load

**Comment by hatrena** [comment]
I have `slsession` variable in my cookie, but it returns me `true` for `isEmpty()`

**Comment by Ocramius** [comment]
@hatrena did the example above work, first of all? I'm trying to understand if this is an environment issue or an integration issue.

**Comment by hatrena** [comment]
The example did not work,  but i added those 2 extra libraries in the `composer.json` and created the `SessionMiddleware` in the way explained in the example. this way worked!. thanks

**Comment by Ocramius** [comment]
The fact that the examples won't work bothers me. Do the unit tests pass?

**Comment by hatrena** [comment]
I have added it to the unit test, assertion process failed since it could not get content from parsed token.

**Comment by Ocramius** [comment]
Which test failed?

**Comment by hatrena** [comment]
I ran a middleware test with mocking the request to get the attribute `SessionMiddleware::SESSION_ATTRIBUTE`

**Comment by Ocramius** [comment]
I'm asking about the tests provided with this package :-)

**Comment by hatrena** [comment]
That test passed!

**Comment by mikemix** [comment]
Well I had same problem too. Turned out since I use it over HTTP on my dev server and not HTTPS, the `slsession` cookie has `secure` flag set so it does get transmitted to the server.

**Comment by Ocramius** [comment]
That is intentional: do not use this sort of cookies without TLS.

**Comment by mikemix** [comment]
Yeah it would be nice though to disable this while in dev mode ;)

**Comment by Ocramius** [comment]
See the example dir on how to do that: works without https

**Comment by mikemix** [comment]
thx @Ocramius great work by the way!

**Comment by lcobucci** [comment]
Closing since the issue was the "secure" flag (which is mentioned on documentation).
